apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: build-image
spec:
  templates:
  - name: build-image
    inputs:
      parameters:
      - name: app_repo
      - name: image_owner
      - name: image_name
      - name: image_tag
    container:
      image: gcr.io/kaniko-project/executor:debug
      command: [/kaniko/executor]
      args:
      - --context={{inputs.parameters.app_repo}}
      - --destination={{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:{{inputs.parameters.image_tag}}
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/