apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: java-jdk-17
spec:
  templates:
  - name: java-jdk-17
    inputs:
      parameters:
      - name: command
    container:
      image: eclipse-temurin:17-jdk-alpine
      command: [sh, -c]
      args:
      - "cd /mnt/vol && {{inputs.parameters.command}}"
      volumeMounts:
        - name: repodir
          mountPath: /mnt/vol