apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: update-manifest-version
spec:
  templates:
  - name: update-manifest-version
    inputs:
      parameters:
      - name: environment
      - name: repo_owner
      - name: repo_name
      - name: image_owner
      - name: image_name
      - name: tag
    script:
      image: bitnami/git:2.41.0
      command: [sh]
      source: |
        set -e
        git clone https://$(cat /.github/token)@github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}
        cd {{inputs.parameters.repo_name}}
        sleep 2
        echo ORIGINAL:
        cat k8s/{{inputs.parameters.environment}}.yaml
        echo DEPLOY:
        cat k8s/{{inputs.parameters.environment}}.yaml | sed -e "s@image: {{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:.*@image: {{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:{{inputs.parameters.tag}}@g" | tee k8s/{{inputs.parameters.environment}}.yaml
        git config user.name "$(cat /.github/user)"
        git config user.email "$(cat /.github/email)"
        git add k8s/{{inputs.parameters.environment}}.yaml
        git commit -m "Upgraded k8s/{{inputs.parameters.environment}}.yaml with the tag {{inputs.parameters.tag}}"
        git push
      volumeMounts:
      - name: github-access
        mountPath: /.github/